# Generated by Django 3.2.2 on 2021-10-25 06:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 10, 25))),
                ('time', models.TimeField(default=datetime.time(11, 59, 15, 876498))),
                ('target', models.SmallIntegerField()),
                ('achieved', models.SmallIntegerField()),
                ('error', models.SmallIntegerField(default=0)),
                ('work_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
