# Generated by Django 3.2.2 on 2021-10-12 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 10, 12))),
                ('time', models.TimeField(default=datetime.time(5, 59, 0, 519191))),
                ('target', models.SmallIntegerField()),
                ('achieved', models.SmallIntegerField()),
                ('error', models.SmallIntegerField(default=0)),
                ('work_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=20)),
            ],
        ),
    ]
